name: Create Release

on:
  workflow_dispatch:
    inputs:
      reset_demo:
        default: 'false'
        required: true
        description: 'Reset the demo environment.'

jobs:
  build:
    # if: 'github.event.release.prerelease'
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Echo test
        run: echo ${{ github.event }}

      - name: Get Release
        uses: actions/github-script@v3
        with:
          script: |
            const release = await github.repos.getReleaseByTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: context.ref
            });
            console.log(release);
      # - name: Deploy
      #   run: |
      #     read -sp "Azure password: " AZ_PASS && echo && az login --service-principal -u ${{ secrets.TEAMCLOUD_CI_USERNAME }} -p ${{ secrets.TEAMCLOUD_CI_PASSWORD }} --tenant ${{ secrets.TEAMCLOUD_CI_TENANT }}
      #     az extension add --source ... -y
      #     az tc deploy --subscription ${{ secrets.TEAMCLOUD_CI_SUBSCRIPTION }} -g ... --pre
      # - name: Trigger Publish
      #   uses: actions/github-script@v3
      #   with:
      #     github-token: ${{ secrets.TEAMCLOUD_PAT }}
      #     script: |
      #       github.actions.createWorkflowDispatch({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         workflow_id: 'release.yml',
      #         ref: 'v${{ steps.gitversion.outputs.majorMinorPatch }}',
      #       });
