name: Create Release

on:
  workflow_dispatch:
    inputs:
      reset_demo:
        default: 'false'
        required: true
        description: 'Reset the demo environment.'

jobs:
  build:
    # if: 'github.event.release.prerelease'
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Echo test
        run: echo ${{ github.event }}

      - name: Trigger Publish Test
        uses: actions/github-script@v3
        with:
          # github-token: ${{ secrets.TEAMCLOUD_PAT }}
          script: console.log(context)
        # github.actions.createWorkflowDispatch({
        #   owner: context.repo.owner,
        #   repo: context.repo.repo,
        #   workflow_id: publish_release.yml,
        #   ref,
        # });

      # - name: Deploy
      #   run: |
      #     read -sp "Azure password: " AZ_PASS && echo && az login --service-principal -u ${{ secrets.TEAMCLOUD_CI_USERNAME }} -p ${{ secrets.TEAMCLOUD_CI_PASSWORD }} --tenant ${{ secrets.TEAMCLOUD_CI_TENANT }}
      #     az extension add --source ... -y
      #     az tc deploy --subscription ${{ secrets.TEAMCLOUD_CI_SUBSCRIPTION }} -g ... --pre
